apiVersion: v1
kind: Service
metadata:
  name: edgex-support-notifications
spec:
  selector:
    app: edgex-support-notifications
  ports:
  - name: http
    port: 48060
    protocol: TCP
    targetPort: 48060

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-support-notifications
spec:
  selector:
    matchLabels: 
      app: edgex-support-notifications
  template:
    metadata:
      labels: 
        app: edgex-support-notifications
    spec:
      hostname: edgex-support-notifications
      containers:
      - name: edgex-support-notifications
        image: edgexfoundry/docker-support-notifications-go:1.2.1
        imagePullPolicy: IfNotPresent
        env:
          - name: Service_Host
            value: "edgex-support-notifications"
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: Registry_Host
            value: "edgex-core-consul"
          - name: Clients_CoreData_Host
            value: "edgex-core-metadata"
          - name: Databases_Primary_Type
            value: "mongodb"
          - name: Databases_Primary_Host
            value: "edgex-mongo"
          - name: Databases_Primary_Port
            value: "27017"
          - name: Logging_EnableRemote
            value: "false"
        ports:
        - name: http
          protocol: TCP
          containerPort: 48060
