apiVersion: v1
kind: Service
metadata:
  name: edgex-support-scheduler
spec:
  selector:
    app: edgex-support-scheduler
  ports:
  - name: tcp-48085
    port: 48085
    protocol: TCP
    targetPort: 48085

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-support-scheduler
spec:
  selector:
    matchLabels: 
      app: edgex-support-scheduler
  template:
    metadata:
      labels: 
        app: edgex-support-scheduler
    spec:
      hostname: edgex-support-scheduler
      containers:
      - name: edgex-support-scheduler
        image: edgexfoundry/docker-support-scheduler-go:1.2.1
        imagePullPolicy: IfNotPresent
        env:
          - name: Service_Host
            value: "edgex-support-scheduler"
          - name: IntervalActions_ScrubPushed_Host
            value: "edgex-core-data" 
          - name: IntervalActions_ScrubAged_Host
            value: "edgex-core-data" 
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: Registry_Host
            value: "edgex-core-consul"
          - name: Clients_CoreData_Host
            value: "edgex-core-metadata"
          - name: Databases_Primary_Type
            value: "mongodb"
          - name: Databases_Primary_Host
            value: "edgex-mongo"
          - name: Databases_Primary_Port
            value: "27017"
          - name: Logging_EnableRemote
            value: "false"
        ports:
        - name: tcp-48085
          protocol: TCP
          containerPort: 48085
