apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-ui-go
spec:
  selector:
    matchLabels: 
      app: edgex-ui-go
  template:
    metadata:
      labels: 
        app: edgex-ui-go
    spec:
      hostname: edgex-ui-go
      containers:
      - name: edgex-ui-go
        image: edgexfoundry/docker-edgex-ui-go:1.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          protocol: TCP
          containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: edgex-ui-go
spec:
  type: NodePort
  selector:
    app: edgex-ui-go
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 30040