apiVersion: v1
kind: Service
metadata:
  name: edgex-core-command
spec:
  selector:
    app: edgex-core-command
  ports:
  - name: http
    port: 48082
    protocol: TCP
    targetPort: 48082

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-core-command
spec:
  selector:
    matchLabels: 
      app: edgex-core-command
  template:
    metadata:
      labels: 
        app: edgex-core-command
    spec:
      hostname: edgex-core-command
      containers:
      - name: edgex-core-command
        image: edgexfoundry/docker-core-command-go:1.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          protocol: TCP
          containerPort: 48082
        env:
          - name: Service_Host
            value: "edgex-core-command"
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: Registry_Host
            value: "edgex-core-consul"
          - name: Databases_Primary_Type
            value: "mongodb"
          - name: Databases_Primary_Host
            value: "edgex-mongo"
          - name: Databases_Primary_Port
            value: "27017"
          - name: Logging_EnableRemote
            value: "false"
          # - name: Clients_Logging_Host
          #   value: "edgex-support-logging" # un-comment if re-enabling logging service for remote logging