apiVersion: v1
kind: Service
metadata:
  name: edgex-core-consul
spec:
  type: NodePort
  selector:
    app: edgex-core-consul
  ports:
  - name: tcp-8500
    port: 8500
    protocol: TCP
    targetPort: 8500
    nodePort: 30085
  - name: tcp-8400
    port: 8400
    protocol: TCP
    targetPort: 8400
    nodePort: 30084

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-core-consul
spec:
  selector:
    matchLabels: 
      app: edgex-core-consul
  template:
    metadata:
      labels: 
        app: edgex-core-consul
    spec:
      hostname: edgex-core-consul
      containers:
      - name: edgex-core-consul
        image: edgexfoundry/docker-edgex-consul:1.2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: EDGEX_DB
            value: "mongo"
          - name: EDGEX_SECURE
            value: "false"
        ports:
        - name: tcp-8500
          protocol: TCP
          containerPort: 8500
        - name: tcp-8400
          protocol: TCP
          containerPort: 8400
        volumeMounts:
        - name: consul-config
          mountPath: /consul/config
        - name: consul-data
          mountPath: /consul/data
      volumes:
         - name: consul-config
           hostPath:
             path: /consul/config
             type: DirectoryOrCreate
         - name: consul-data
           hostPath:
             path: /consul/data
             type: DirectoryOrCreate
