apiVersion: v1
kind: Service
metadata:
  name: edgex-mongo
spec:
  selector:
    app: edgex-mongo
  ports:
  - name: http
    protocol: TCP
    port: 27017
    targetPort: 27017  

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-mongo
spec:
  selector: 
    matchLabels:
      app: edgex-mongo
  template:
    metadata:
      labels:
        app: edgex-mongo
    spec:
      hostname: edgex-mongo
      containers:
      - name: edgex-mongo
        image: edgexfoundry/docker-edgex-mongo:1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        env:
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: Registry_Host
            value: "edgex-core-consul"
          - name: Databases_Primary_Type
            value: "mongodb"
          - name: Databases_Primary_Host
            value: "edgex-mongo"
          - name: Databases_Primary_Port
            value: "27017"
          - name: Logging_EnableRemote
            value: "false"
        volumeMounts:
        - name: db-data
          mountPath: /data/db
      volumes:
         - name: db-data
           hostPath:
             path: /data/db
             type: DirectoryOrCreate                 