apiVersion: v1
kind: Service
metadata:
  name: edgex-redis
spec:
  selector:
    app: edgex-redis
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379  

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-redis
spec:
  selector: 
    matchLabels:
      app: edgex-redis
  template:
    metadata:
      labels:
        app: edgex-redis
    spec:
      hostname: edgex-redis
      containers:
      - name: edgex-redis
        image: redis:5.0.8-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: Registry_Host
            value: "edgex-core-consul"
          - name: Databases_Primary_Type
            value: "mongodb"
          - name: Databases_Primary_Host
            value: "edgex-redis"
          - name: Databases_Primary_Port
            value: "27017"
          - name: Logging_EnableRemote
            value: "false"
        volumeMounts:
        - name: db-data
          mountPath: /data/db
      volumes:
         - name: db-data
           hostPath:
             path: /data/db
             type: DirectoryOrCreate                 