apiVersion: v1
kind: Service
metadata:
  name: edgex-sys-mgmt-agent
spec:
  selector:
    app: edgex-sys-mgmt-agent
  ports:
  - name: http
    port: 48090
    protocol: TCP
    targetPort: 48090

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-sys-mgmt-agent
spec:
  selector:
    matchLabels: 
      app: edgex-sys-mgmt-agent
  template:
    metadata:
      labels: 
        app: edgex-sys-mgmt-agent
    spec:
      hostname: edgex-sys-mgmt-agent
      containers:
      - name: edgex-sys-mgmt-agent
        image: edgexfoundry/docker-sys-mgmt-agent-go:1.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          protocol: TCP
          containerPort: 48090
        env:
          - name: Service_Host
            value: "edgex-sys-mgmt-agent"
          - name: ExecutorPath
            value: "/sys-mgmt-executor"
          - name: MetricsMechanism
            value: "executor"
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: Registry_Host
            value: "edgex-core-consul"
          - name: Databases_Primary_Type
            value: "mongodb"
          - name: Databases_Primary_Host
            value: "edgex-mongo"
          - name: Databases_Primary_Port
            value: "27017"
          - name: Logging_EnableRemote
            value: "false"
          # - name: Clients_Logging_Host
          #   value: "edgex-support-logging" # un-comment if re-enabling logging service for remote logging
         volumeMounts:
          - name: docker
            mountPath: /var/run/docker.sock
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
            type: File