apiVersion: v1
kind: Service
metadata:
  name: edgex-app-service-configurable-rules
spec:
  selector:
    app: edgex-app-service-configurable-rules
  ports:
  - name: http
    port: 48100
    protocol: TCP
    targetPort: 48100

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-app-service-configurable-rules
spec:
  selector:
    matchLabels: 
      app: edgex-app-service-configurable-rules
  template:
    metadata:
      labels: 
        app: edgex-app-service-configurable-rules
    spec:
      hostname: edgex-app-service-configurable-rules
      containers:
      - name: edgex-app-service-configurable-rules
        image: edgexfoundry/docker-app-service-configurable:1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          protocol: TCP
          containerPort: 48100
        env:
          - name: Service_Host
            value: "edgex-app-service-configurable-rules"
          - name: edgex_profile
            value: "rules-engine"
          - name: MessageBus_SubscribeHost_Host
            value: "edgex-core-data"
          - name: Binding_PublishTopic
            value: "events"
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: Registry_Host
            value: "edgex-core-consul"
          - name: Databases_Primary_Type
            value: "mongodb"
          - name: Databases_Primary_Host
            value: "edgex-mongo"
          - name: Databases_Primary_Port
            value: "27017"
          - name: Logging_EnableRemote
            value: "false"
          # - name: Clients_Logging_Host
          #   value: "edgex-support-logging" # un-comment if re-enabling logging service for remote logging